CREATE TABLE OWNER (
    OWN_NUM NUMBER(38,0) PRIMARY KEY NOT NULL,
    OWN_LAST_NAME VARCHAR2(25) NOT NULL,
    OWN_FIRST_NAME VARCHAR2(25) NOT NULL,
    OWN_STREET VARCHAR2(25) NOT NULL,
    OWN_CITY VARCHAR2(25) NOT NULL,
    OWN_STATE VARCHAR2(3) NOT NULL );
    

CREATE TABLE VEHICLE (
    VEH_NUM NUMBER(38,0) PRIMARY KEY NOT NULL,
    VEH_MAKE VARCHAR2(25) NOT NULL,
    VEH_MODEL VARCHAR2(25) NOT NULL,
    VEH_YEAR VARCHAR2(5) NOT NULL,
    VEH_COLOR VARCHAR2(25) NOT NULL,
    VEH_PLATE VARCHAR2(25) NOT NULL,
    VEH_STATE VARCHAR2(3) NOT NULL,
    OWN_NUM NUMBER(38,0),
    FOREIGN KEY(OWN_NUM) REFERENCES OWNER );
    
CREATE TABLE REQUEST (
    REQ_NUM NUMBER(38,0) PRIMARY KEY NOT NULL,
    REQ_DATE DATE,
    VEH_NUM NUMBER(38,0),
    FOREIGN KEY(VEH_NUM) REFERENCES VEHICLE );
    
CREATE TABLE SERVICE (
    SVC_NUM NUMBER(38,0) PRIMARY KEY NOT NULL,
    SVC_NAME VARCHAR2(25) NOT NULL,
    SVC_EST_HOURS NUMBER(3,1) DEFAULT 00.0 NOT NULL,
    SVC_EST_PRICE NUMBER (6,2) DEFAULT 0.00 NOT NULL );
    
CREATE TABLE LINE (
    REQ_NUM  NUMBER(38,0) NOT NULL,
    LIN_NUM NUMBER(38,0) NOT NULL,
    SVC_NUM NUMBER(38,0) NOT NULL,
    LIN_HOURS NUMBER(3,1),
    LIN_PRICE NUMBER(6,2),
    PRIMARY KEY(REQ_NUM, LIN_NUM),
    FOREIGN KEY(REQ_NUM) REFERENCES REQUEST,
    FOREIGN KEY(SVC_NUM) REFERENCES SERVICE );
