INSERT INTO OWNER VALUES('100', 'ADNEY', 'BRUCE', '200 LEMON DRIVE', 'HARRISBURG', 'PA');  
INSERT INTO OWNER VALUES('101', 'ANDERSON','WILLIAM', '84562 WILSON STREET', 'HARRISBURG', 'PA');
INSERT INTO OWNER VALUES('102', 'BLAKE', 'MARY','7845 RIVERSIDE', 'YORK', 'PA');
INSERT INTO OWNER VALUES('103', 'JUAREZ', 'MARISSA', '961 LAKEWOOD DRIVE', 'YORK', 'PA');
INSERT INTO OWNER VALUES('104', 'KELLY', 'DANIEL', '1654 GARLAND AVENUE', 'WAYNE', 'NJ');
INSERT INTO OWNER VALUES('105', 'TRENT', 'PETER', '3562 WATERS WAY', 'WAYNE', 'NJ');
INSERT INTO OWNER VALUES('106', 'NORTON', 'BECKY', '4286 OAK ROAD', 'WAYNE', 'NJ');


